### PR TITLE
End Round Vote Timer + Multivote adjustment

### PR DESCRIPTION
**Pull request by EmilitiaEnnehrt**
## Changes End Round Vote

Changes minimum time until a vote for end round can be called from 4 hours 15 minutes to 2 hours 30 minutes. 
Also Disallows people to vote for both end round and continue options at the same time which seems to break undoing votes.

Currently, I'm not sure how to implement automatic vote call after a certain amount of time.

## Changelog
:cl:
config: end round vote timer and behavior
/:cl:

### CODE REVIEW

**Review by valkyria-gk — APPROVED** [review]

**Comment by valkyria-gk** [comment]
@Hawk-v3 approve the workflow or so help letting me do it on your behalf.

**Comment by Hawk-v3** [comment]
They should autorun. There's a fail.

**Comment by EmilitiaEnnehrt** [comment]
If I can be pointed to how it can be made to autorun, I'll add that in, but there doesn't seem to be anything within this file.

My current concern is with people testing out the server or cryo'ing early, and me not being able to even vote to restart to play fresh or let other people start a new game.

**Comment by valkyria-gk** [comment]
I think they were referring to the CI checks?

Just rerun the checks again @Hawk-v3, the failure is evidentially random.

**Review by Hawk-v3 — APPROVED** [review]

**Pull request merged**
