### PR TITLE
Set respawn timer to 2 minutes.

### PR DESCRIPTION
**Pull request by Awesome4Real**
## About The Pull Request
<details>
<summary>
	About The Pull Request
Set the respawn timer to two minutes. It would be zero minutes, but the function acts up when it is set to zero.
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

### CODE REVIEW

**Review by Michiyamenotehifunana — CHANGES_REQUESTED** [review]
This change would do nothing as it will be overwritten by the server configuration file's default of 30 minutes. As this is a configuration thingy, it can be changed at any time without a PR, by whoever has TGS access.

**Comment by Awesome4Real** [comment]
i've checked the config folder and it has nothing in there that seems to affect respawn times. I've tested this change ingame and it appears to work just fine. can you direct me to the part of the config folder that affects the respawn time?

**Comment by Michiyamenotehifunana** [comment]
Right, the example config.txt does not have the respawn_delay option listed in it for whatever reason, but the code will still check for it regardless. It would still be far easier to simply add that to the live server's config.txt and set it to an arbitrarily low value from there.

**Comment by Michiyamenotehifunana** [comment]
Closing as the config change is working on the live server.

**Pull request closed without merging**
