### PR TITLE
Lynx's Chaos and Storyteller additions 

### PR DESCRIPTION
**Pull request by Lynx22330**
## About The Pull Request
<details>
<summary>
	Introduces Chaos via incremental gains per hour based on how many players are currently present in the server (at a rate of (max_players * 0.1), if there are 8 players, it increases by 0.8 chaos per hour.
	Also includes the ability to vote for decreasing, or resetting chaos (So that the server can choose to balance how they want to play today, rather than make it something forced.)
	If there are 50 players, (which as of currently when this PR was made, may not occur for a long time), chaos will always be set to 5 during each hourly tick, but this should not be a problem thanks to high player count keeping everyone... Relatively alive. This could just as well be dropped to 0.05 as well if that ever occurs.
	The Warrior storyteller has been buffed to encourage more events to occur more frequently, being very aggressive, and is the only one changed for now. This can be asked to be removed and put into another PR upon request so that this can be tested separately. 
	Yes. I have tested this locally. Voting works as intended, same with the timer. (which should work every hour!)
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

### CODE REVIEW

**Comment by Lynx22330** [comment]
Since the changelog didn't work, here is the changelog simplified.

Added chaos gain overtime.
Re-introduced some more passive mobs to the mundane events when infestations occur, to help offset the new chaos multipliers.
Warrior storyteller has also been altered to be more... aggressive with events, to help encourage many more enemies.
Added the ability to vote to change chaos, by decreasing, or resetting it to 0.

**Comment by EmilitiaEnnehrt** [comment]
I'm requesting that if this is to be merged, run a testmerge first.
1. Touching on balancing is a sensitive subject until the developer are fully knowledgable with the codebase and the feel without the feedback of actual players. If this isn't the guaranteed case, a testmerge should be run to get player feedback.
2. I have always been a fan of allowing PvE to be opted in, or at least the one that requires participation be either easy (burrow mobs in colony) or blob/hivemind (specifically require a number of combat jobs). How would this upset the balance of colony-side PvE suddenly being harder?
3. In the point made about the server wanting to play how they want today, would a zero hourly increase and Chaos Increase vote that already exist be more suitable?
4. How would this affect the late-joiners in terms of balance against mobs using starting equipment and stats?

**Comment by JoltzW** [comment]
I will comment that there is already a vote to up the chaos level if players want it. Another important factor is how many combatants there are. Max players does not equal the number of armed and willing to fight players there are. Some come for RP, some come to do low level jobs like botanist, cook, or other roles like that. With this i fear those players would be punished for joining a round with more people which is usually the best time to do their jobs. For a combatant, a random empress spawn is fun. For a non-combatant it can be rage inducing or even demoralizing.

**Comment by Lynx22330** [comment]
Closing this for now until I rework story teller a little more.

Plans are to move infestations/burrows/migrations into Maint Tunnels only, and to introduce new events within the colony itself that can offer new PvE encounters that do not rely on Burrows. 

Burrows should only occur outside of the Colony as a whole, underground in maints. I would really like to go over maints and possibly add more areas or improve its size and make it feel more like a maze when people go down there. I know that deep maints is randomly generated iirc, and to reflect that, having a wide and spanning normal maints is something of interest.

**Comment by Lynx22330** [comment]
Here. The PR is up and should be ready? I don't believe there are any conflicts. Could be wrong.

**Comment by Lynx22330** [comment]
Should be good to go. Changes are set and ready.

Test merge when able to, thanks in advance. Im so tired after looking at damage calculations... ;u;"

**Review by Takykardi — APPROVED** [review]
Code passes the sniff test. However the damage values and etc. are going to need testing to see if the difficulty is balanced. We should balance to the average skill level, not to the hardcore gamer-game skill level.

**Comment by Lynx22330** [comment]
closing for now

**Pull request closed without merging**
