### PR TITLE
Adds Skull Masks Markings

### PR DESCRIPTION
**Pull request by SigDoesCode**
Adds three different skull masks and their kintsugi compatriots.

## About The Pull Request
<details>
<summary>
	About The Pull Request
Adds a trio of skull masks and their accompanying kintsugi sprites for character creation. I wanted to add these, so I did. 
</summary>
<hr>

Adds three skull masks, each with a regular and kintsugi variant. 
Full Skull Mask, with a lower jaw. 
image
The full skull mask in kintsugi.
image
The half skull mask, without a lower jaw.
image
The half skull mask in kintsugi form.
image
The quarter skull mask, no lower jaw nor back of the head.
image
the quarter skull mask in kintsugi form
image

Each of these masks layers with hair. Here is the quarter skull kintsugi mask with the beehive 2 hair.
image

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by SigDoesCode** [comment]
They also layer with other markings, because they're markings.

**Comment by Hawk-v3** [comment]
@Michiyamenotehifunana There's another set of Meat runtimes?

**Comment by valkyria-gk** [comment]
> @Michiyamenotehifunana There's another set of Meat runtimes?

https://github.com/Equinox-SS13/equinox-sojourn/blob/186408331b41af3126522f290a37f1f056494191/code/modules/reagents/reagent_containers/food/snacks/meat.dm#L24

`unnatural_mutations` is null somehow. Try restart the tests?

**Comment by Hawk-v3** [comment]
@SigDoesCode Can you check the merge issue?

**Comment by SigDoesCode** [comment]
> @SigDoesCode Can you check the merge issue?

what the fuck? I didn't touch any meat files, why is this runtiming? 
I'll take a look tomorrow morning, sorry!

**Comment by valkyria-gk** [comment]
> > @SigDoesCode Can you check the merge issue?
> 
> what the fuck? I didn't touch any meat files, why is this runtiming? I'll take a look tomorrow morning, sorry!

It happens pretty randomly, don't worry about it. Focus on the merge conflict instead.

**Comment by Michiyamenotehifunana** [comment]
Looks like #9 did not actually fix it, meat_source wasn't null, unnatural_mutations was. I'll have to tack on more if() sanity checks then.

**Comment by Hawk-v3** [comment]
image
@SigDoesCode Tori changed this file too. Please check this file.

**Comment by SigDoesCode** [comment]
I think I fixed it? I don't have a ton of experience fixing merge conflicts even if I tend to run into them a lot.

**Comment by valkyria-gk** [comment]
Re-approve workflows @Hawk-v3

**Review by valkyria-gk — APPROVED** [review]

**Review by Hawk-v3 — APPROVED** [review]

**Pull request merged**
