### PR TITLE
Reverts Sojourn's PR 5029 armour changes

### PR DESCRIPTION
**Pull request by Delams-The-SM**
## About The Pull Request
<details>
<summary>
	This PR aims to revert armour changes that happened in https://github.com/sojourn-13/sojourn-station/pull/5029
</summary>
<hr>

This draft is here mostly to make it visible (not just a branch on my fork), not sure why I have done it honestly but I was bored, I done it, and now it is here.

<hr>
</details>

This draft does the following :
- Reverts the armour code to pre 5029 (Bulk combat changes; Armor Divisors, bullet balance, mob health/armor, etc.) PR state
- Keeps most of other changes that the PR made (like global health modifiers for PVE factions or blocking)
- Adds ABSOLUTE armour to the armour calculation (currently disabled, controlled by ABSOLUTE_ARMOR_EFFICIENCY variable)
- Adds RELATIVE_ARMOR_EFFICIENCY and ABSOLUTE_ARMOR_EFFICIENCY both being multipliers for their respective armour type

What is not yet there :
- Overpenetration/halloss damage in PVE
- ablative_armor is not accounted for in armour calculations
- ALOT OF TESTING
- ALOT OF CLEANUP (Both armor_penetration and armor_list should have their values set by defines among other things)

### SO WHY DID I DO IT
I don't know, but if I did it already might as well keep it around as a draft ? perhaps it will be educational, or something

Technically we could merge it (after fixes) but as far as I understand we are still testing and figuring out current armour system.

There probably are broken things, it feels like I frankensteined alot of things together into a lump that works.
code\modules\mob\living\living_defense.dm above all will need a look at, alot of commented out code for PVE interactions especially

## Changelog
:cl:
add: Added ABSOLUTE and RELATIVE armour to armour system
del: Removed old code for armour
tweak: tweaked armour
balance: rebalanced armour back to what it was (more or less)
/:cl:

### CODE REVIEW

**Comment by SigDoesCode** [comment]
Added "Bugfix", "Not ready for merge", and "rebalance" labels. Bugfix because of fixing bugs in armor code, not ready for merge because overpen/halloss not being calculated in PvE and ablative_armor not being added, plus cleanup needed for proper merge. Rebalance added because this would be a rebalance of the armor system.

I think there's currently a PR up that fixes Soj's flat-reduction armor system, so we might try that for a bit and see what's going on with that and how it feels before working on a full revert. I'll ask some of the other devs.

**Comment by SigDoesCode** [comment]
> There probably are broken things, it feels like I frankensteined alot of things together into a lump that works. code\modules\mob\living\living_defense.dm above all will need a look at, alot of commented out code for PVE interactions especially

Also it can't possibly be worse than Soj shipping their armor rebalance while *not having superior mobs considered in armor calculations at all*, so I wouldn't worry about having some Frankenstein code on a draft/unmerged PR at the moment. XD

**Comment by Takykardi** [comment]
Okay, note for testing on this- apparently Soj also redid weapons/tool mods under these, so we'll need to check _those_ for function. Shouldn't be too difficult, just. Blargh.

**Comment by valkyria-gk** [comment]
Merged a PR that caused a MC on this. Fixed it for you.

**Comment by Delams-The-SM** [comment]
At this point this PR just requires a lot of testing, it is possible that I have missed something at some point and haven't thought about it.

**Review by Takykardi — APPROVED** [review]

**Comment by SigDoesCode** [comment]
Ok I figured out why things are always overpenning. I think. 

This block needs to be added to Living_defense.dm, right after the armor effectiveness calculation block. 
```	// Returns if a projectile should continue travelling
	if(return_continuation)
		var/obj/item/projectile/P = used_weapon
		P.damage_types = dmg_types
		if(sharp)
			var/remaining_dmg = 0
			for(var/dmg_type in dmg_types)
				remaining_dmg += dmg_types[dmg_type]
			return ((total_dmg / 2 < remaining_dmg && remaining_dmg > mob_size) ? PROJECTILE_CONTINUE : PROJECTILE_STOP)
		else return PROJECTILE_STOP

	return dealt_damage
```

this should allow it to actuall do the proper proj stopping.

**Review by Michiyamenotehifunana — APPROVED** [review]

**Pull request merged**
